### ISSUE TITLE
1.20.4 Support ?

### ISSUE THREAD

**Issue by MerlinTheHobkin** [ryanbester/keepcommandhistory#2]

**Comment by ryanbester** [comment]
I'm currently in the process of upgrading to 1.20.4 now. I had to migrate the project to a different build system with different mappings, hence the delay.

**Comment by ryanbester** [comment]
[Version 1.0.3](https://github.com/ryanbester/keepcommandhistory/releases/tag/1.0.3) has been released with support for Minecraft 1.20.4.

**Comment by MerlinTheHobkin** [comment]
Thx

Ryan Bester ***@***.***> schrieb am Fr., 9. Feb. 2024, 22:36:
